name: Test and Deploy to GitHub Pages

on:
  push:
    branches: [gh-site]
  pull_request:
    branches: [gh-site]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint
      - name: Run Lint (ESLint)
        run: npm run lint

      # Run Vitest (unit tests)
      - name: Run Unit Tests
        run: npm run test

      # Build the Vite site
      - name: Build Vite site
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
